services:      
  directus:
    image: directus/directus:latest
    container_name: directus
    ports:
      - 8055:8055
    restart: always
    x-tinkr:
      cpu: 768
      memory: 960
      depends_on:
        - mariadb
      environment: 
        - DB_HOST=<hostname:mariadb>
      network:
        public: true  # Indicates this service is accessible in public subnets
      ports:
        directus-port:   # Define a unique port name
          port: 8055
          protocol: http
          public: true
          healthcheck:
            timeout: 10
            success_code: "301-302"
            interval: 120
            path: /
            retries: 3
    networks:
      - database
    environment:
      - KEY=3579757c-be70-4eb3-8bc0-2d089e1acde5
      - SECRET=4edf7e4a-274c-4b66-971b-83e0848710e7
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=t1nkrDirectus
      - DB_CLIENT=mysql
      - DB_HOST=mariadb
      - DB_DATABASE=directus
      - DB_USER=directus
      - DB_PASSWORD=directus
      - DB_PORT=3306
      
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    x-tinkr:
      cpu: 768
      memory: 960
      network:
        public: false  # Indicates this service is accessible in private subnets
      ports:
        mariadb:
          port: 3306
          protocol: tcp
          public: false
    environment:
      - MYSQL_ROOT_PASSWORD=directus
      - MYSQL_DATABASE=directus
      - MYSQL_USER=directus
      - MYSQL_PASSWORD=directus
    networks:
      - database
    ports:
      - 3306:3306

networks:
  database:
    driver: bridge

volumes:
  db_data:
